### PR TITLE
Release world generation

### PR DESCRIPTION
**Pull request by BlueStaggo**
*Note: I had to make a new pull request because Github was stupid and closed it when I renamed the main branch. Original pull request: #113*

One of the main missing features of Modern Beta is the ability to generate worlds from Beta 1.8 to 1.12.2. I assume this has been left out because it is a complicated task. Well, I took on that task, and it payed off! New presets available include Beta 1.8.1, 1.0.0, 1.1, 1.2.5, 1.6.4 and 1.12.2 (currently a bit inaccurate). In addition to this, I also fixed surface rules in beta world generation and updated the mod to 1.20.4 (#131).

## Screenshots

**Beta 1.8 world generation with old swamps**

**Swampland next to ice plains in a 1.0.0 world**

**Mushroom Island in the famous 4 seed using the 1.2.5 generator**

**Desert and jungle with hill variants from 1.3.1-1.6.4**

**Old growth pine taiga bordering a few other biomes from 1.12.2**
image

**Badlands in Beta 1.7.3 world generation with fixed surface rules**
image

### CODE REVIEW

**Comment by lowercasebtw** [comment]
dude you are heaven 

although  I wish I could get 1.16.5 world gen (basically 1.7-1.12), but as just a datapack

Does this build currently?!?!?!

**Comment by lowercasebtw** [comment]
I miss the old caves, ravines & wish there was a option to disable generation below y 0

**Comment by BlueStaggo** [comment]
@lowercasebtw In case you didn't know yet, there is now an option to disable generation below Y 0 in my fork available here: https://modrinth.com/mod/moderner-beta

**Comment by lowercasebtw** [comment]
> @lowercasebtw In case you didn't know yet, there is now an option to disable generation below Y 0 in my fork available here: https://modrinth.com/mod/moderner-beta

:D

**Comment by BlueStaggo** [comment]
Ok at this point I think my fork has overtaken the original mod...

**Comment by Delvin4519** [comment]
This mod is currently used in the Re-Console modpack, and I wonder if it would be possible to replicate Legacy Console Worlds in an issue [I posted here](https://github.com/Wilyicaro/Legacy-Minecraft/issues/483#issuecomment-2187215144). One thing that is bothersome is the lack of an "issues" page on the forked page.

image
image

**Comment by lowercasebtw** [comment]
> Ok at this point I think my fork has overtaken the original mod...

I was wondering if you know how to do world gen in spigot, I would love to see this as a plug-in that I could use on my server, without having people to install moderner beta, and or using fabric server software etc

**Comment by AffableMan22** [comment]
I've been using your fork and it's honestly a godsend in how accurate it is, are you ever going to add pre-cave and cliffs bedrock edition generation?

**Comment by BlueStaggo** [comment]
> I've been using your fork and it's honestly a godsend in how accurate it is, are you ever going to add pre-cave and cliffs bedrock edition generation?

Very likely not since it's just the same as Java Edition 1.17's world generation but seeded differently.

**Comment by BlueStaggo** [comment]
Yeah the original Modern Beta isn't going anywhere so it's best to just focus on my fork instead :P

**Comment by b3spectacled** [comment]
Hi there, many apologies for not getting back to you after nearly a year!

Right as I was going to get back into the mod, I ended up catching COVID which put me out of commission for over a month and then after that life got in the way.

I see you've got a great fork going now that improves on everything I wanted to address and more, so I feel like it's time to put this project to rest. Thank you for picking this up and good luck!

**Pull request closed without merging**
